services:
  - type: web
    name: diary-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: free
    region: oregon
    buildFilter:
      paths:
        - app/backend_api/**
    autoDeploy: true
    repo: https://github.com/username/my-repo
    rootDir: app/backend_api
